### ISSUE TITLE
Documentation DIND var

### ISSUE THREAD

**Issue by stlu1022** [DontShaveTheYak/jenkins-std-lib#281]
Hello everyone,

would it be possible to provide a little more information on the DIND env var that has to be set. Running my Jenkins instance in a pod in a K8s cluster using Docker Desktop on a macOs 13.0.1, I am not quite sure on how to set it up. 

I am using "standard" jenkinsci/jenkins helm chart (adding the needed plugins). 

This is pipeline script I am trying out: 
```
@Library('jenkins-std-lib')
import org.dsty.github.actions.Step
import org.dsty.logging.LogClient

LogClient log = new LogClient(this)

node() {
    Step action = new Step(this)
    Map options
    Map outputs
    
    stage('Docker Action') {
        options = [
            'name': 'Test Docker Action',
            'uses': 'actions/hello-world-docker-action@master',
            'with': [
                'who-to-greet': 'DockerAction'
            ] 
        ]
        log.info("Running Action: \n${options}")
        outputs = action(options)
        log.info("Returned outputs:\n${outputs}")
    }
}
```
This is the console output: 
```
Started by user [Jenkins Admin](http://127.0.0.1:8080/user/admin)
Loading library jenkins-std-lib@master
Attempting to resolve master from remote references...
 > git --version # timeout=10
 > git --version # 'git version 2.30.2'
 > git ls-remote -h -- https://github.com/DontShaveTheYak/jenkins-std-lib.git # timeout=10
Found match: refs/heads/master revision 009fcae02afac2e88ea5034a35883780368cd808
The recommended git tool is: NONE
No credentials specified
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/DontShaveTheYak/jenkins-std-lib.git
 > git init /var/jenkins_home/workspace/test@libs/8cd9defd843f527da319d2f77a7a64d136d96824faa84f46583ced278ed78a33 # timeout=10
Fetching upstream changes from https://github.com/DontShaveTheYak/jenkins-std-lib.git
 > git --version # timeout=10
 > git --version # 'git version 2.30.2'
 > git fetch --no-tags --force --progress -- https://github.com/DontShaveTheYak/jenkins-std-lib.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/DontShaveTheYak/jenkins-std-lib.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
Checking out Revision 009fcae02afac2e88ea5034a35883780368cd808 (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 009fcae02afac2e88ea5034a35883780368cd808 # timeout=10
Commit message: "remove dependabot, enable renovate"
[Pipeline] Start of Pipeline
[Pipeline] node
Agent [default-vprbq](http://127.0.0.1:8080/computer/default-vprbq) is provisioned from template default
---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins/jenkins-jenkins-agent: "true"
    jenkins/label-digest: "500b4f18aee87616849e4f4c2435020898e34aa0"
    jenkins/label: "jenkins-jenkins-agent"
  name: "default-vprbq"
  namespace: "default"
spec:
  containers:
  - args:
    - "********"
    - "default-vprbq"
    env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_TUNNEL"
      value: "jenkins-agent.default.svc.cluster.local:50000"
    - name: "JENKINS_AGENT_NAME"
      value: "default-vprbq"
    - name: "JENKINS_NAME"
      value: "default-vprbq"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins/agent"
    - name: "JENKINS_URL"
      value: "http://jenkins.default.svc.cluster.local:8080/"
    image: "jenkins/inbound-agent:4.11.2-4"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    resources:
      limits:
        memory: "512Mi"
        cpu: "512m"
      requests:
        memory: "512Mi"
        cpu: "512m"
    tty: false
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  serviceAccountName: "default"
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"

Running on [default-vprbq](http://127.0.0.1:8080/computer/default-vprbq/) in /home/jenkins/agent/workspace/test
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Docker Action)
[Pipeline] echo
[Info] Running Action: 
[name:Test Docker Action, uses:actions/hello-world-docker-action@master, with:[who-to-greet:DockerAction]]
[Pipeline] echo
[Info] Checking out actions/hello-world-docker-action@master
[Pipeline] dir
Running in /home/jenkins/agent/workspace/test@tmp/hello-world-docker-action
[Pipeline] {
[Pipeline] checkout
The recommended git tool is: NONE
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/actions/hello-world-docker-action
 > git init /home/jenkins/agent/workspace/test@tmp/hello-world-docker-action # timeout=10
Fetching upstream changes from https://github.com/actions/hello-world-docker-action
 > git --version # timeout=10
 > git --version # 'git version 2.30.2'
 > git fetch --tags --force --progress -- https://github.com/actions/hello-world-docker-action +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/actions/hello-world-docker-action # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
Checking out Revision b136eb8894c5cb1dd5807da824be97ccdf9b5423 (origin/master)
 > git rev-parse origin/master^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f b136eb8894c5cb1dd5807da824be97ccdf9b5423 # timeout=10
Commit message: "Merge pull request #3 from lucascosti/patch-1"
[Pipeline] fileExists
[Pipeline] readYaml
[Pipeline] }
[Pipeline] // dir
[Pipeline] echo
[Info] Building Docker Container for hello-world-docker-action
[Pipeline] dir
Running in /home/jenkins/agent/workspace/test@tmp/hello-world-docker-action
[Pipeline] {
[Pipeline] sh
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] sh
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: org.dsty.bash.ScriptError: Script exitCode was 127 and stderr:
/home/jenkins/agent/workspace/test@tmp/hello-world-docker-action@tmp/durable-0372c3ca/script.sh: line 9: docker: command not found
	at org.dsty.bash.BashClient.execute(BashClient.groovy:119)
	at org.dsty.bash.BashClient.silent(BashClient.groovy:85)
	at org.dsty.github.actions.DockerAction.dockerBuild(DockerAction.groovy:75)
	at ___cps.transform___(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:100)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:85)
	at jdk.internal.reflect.GeneratedMethodAccessor208.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:158)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:152)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:152)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:30)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:70)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE
```

Thanks in advance! :)

Greetings,
Luca

**Comment by shadycuz** [comment]
The DIND var is for if you are passing in the HOSTS's docker socket to the JENKINS container and the JENKINS containers "jenkins_home" directory is a volume on the HOST. If that is the case then you should set the DIND directory to the path of the Jenkins_home directory.

In your case:
```
volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"
```

I'm not sure what the path to `workspace-volume` is on the K8 host but that is what you would set for the DIND env var. But maybe you shouldnt...

The DIND var was a hacky workaround to make this work but it doesn't work very well and I'm doing away with it in the next [version](https://github.com/DontShaveTheYak/jenkins-std-lib/releases/tag/untagged-5b8e7104c71852ac0eda). Most of the work was done in #260.

The variable is misnamed, passing in the docker socket from the host is not Docker Inside of Docker (DIND) its really docker alongside of docker. What you really want is DIND. This means you need to install a stand-alone docker daemon inside of Jenkins. My image should work as a drop in replacement for the HELM chart. 

You can see how I did it here. https://github.com/DontShaveTheYak/jenkins-std-lib/blob/develop/docker/prod/Dockerfile

You will also need to change how the container behaves because instead of a single process like Jenkins you will also need to run the docker daemon as well. I choose S6 overlay for this. 

You will either have to build your own custom Jenkins image, or I can push my Jenkins prod image to Docker Hub and you can use it.

**Comment by stlu1022** [comment]
Hi @shadycuz,

thanks for the detailed answer. :)
