### ISSUE TITLE
HTTP request library fails internally if a HTTP response does not contain a 'Content-Type' header

### ISSUE THREAD

**Issue by alacoste** [DontShaveTheYak/jenkins-std-lib#305]
I am experiencing exceptions with the following stacktrace:
```
java.lang.NullPointerException: Cannot invoke method contains() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at org.dsty.http.Requests.execute(Requests.groovy:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.dsty.http.Requests.get(Requests.groovy:84)
```

Given the stacktrace, I think the problematic code is indeed at
https://github.com/DontShaveTheYak/jenkins-std-lib/blob/master/src/org/dsty/http/Requests.groovy#L156
```
if (response.headers?.'Content-Type'.contains('application/json')) {
            JsonSlurperClassic slurper = new JsonSlurperClassic()
            response.json = slurper.parseText(response.body)
        }
```
which can try to call `contains` on a null object

**Comment by shadycuz** [comment]
Your fix has been merged. To easily test the change you can point the library at a branch. 

```Groovy
@Library('my-shared-library@develop')
``` 

I will work on a couple of other things and then we will cut a new release.
